#!/bin/sh -e
HOSTID="$(/bin/sed 's/://g ; s/^.\{6\}//' /sys/class/net/int0/address)"
[ -n "$HOSTID" ] || { echo "No HOSTID"; exit 1; }

/bin/hostname twbox-$HOSTID
/bin/hostname > /etc/hostname

umount /var/host/current 2>/dev/null || true
mount --bind /var/host/twbox-${HOSTID} /var/host/current

[ -L /etc/hosts ] || {
    [ -e /etc/hosts ] && mv /etc/hosts /etc/hosts.o
    ln -s /var/host/current/hosts /etc/hosts
}

[ -L /var/lib/mysql ] || {
    /etc/init.d/mysql stop
    [ -e /var/lib/mysql ] && mv /var/lib/mysql /var/lib/mysql.o
    ln -s /var/host/current/mysql /var/lib/mysql
}
[ -d /var/host/current/mysql ] || {
    mkdir -p /var/host/current/mysql
    mysql_install_db
}

[ -L /etc/nginx/sites-enabled/default ] && rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/tw-proxy /etc/nginx/sites-enabled/tw-proxy
ln -sf /var/host/current/nginx/redirect /etc/nginx/sites-enabled/redirect

[ -L /srv/tutorweb.buildout/buildout.cfg ] || ln -s /var/host/current/buildout.cfg /srv/tutorweb.buildout/buildout.cfg

[ -d /var/host/current/phonehome ] || mkdir -p /var/host/current/phonehome
[ -f /var/host/current/phonehome/id_rsa ] || {
    ssh-keygen -N "" -f /var/host/current/phonehome/id_rsa
    chown nobody:nogroup /var/host/current/phonehome/id_rsa*
}
[ -f /var/host/current/phonehome/config ] || {
    cat <<EOF > /var/host/current/phonehome/config
Host *
    LocalForward 9025 localhost:25
    RemoteForward 9622 localhost:22
    RemoteForward 9680 localhost:80
EOF
}

[ -d /var/host/current/smly ] || {
  mkdir -p /var/host/current/smly
  chown smly:staff /var/host/current/smly
}
