#!/bin/sh
HOSTID="$(/bin/sed 's/://g ; s/^.\{6\}//' /sys/class/net/int0/address)"
[ -n "$HOSTID" ] || { echo "No HOSTID"; exit 1; }

/bin/hostname twbox-$HOSTID
/bin/hostname > /etc/hostname

umount /var/host/current 2>/dev/null || true
mount --bind /var/host/twbox-${HOSTID} /var/host/current
