#!/bin/sh
HOSTID="$(/bin/sed 's/://g ; s/^.\{6\}//' /sys/class/net/int0/address)"
[ -n "$HOSTID" ] || { echo "No HOSTID"; exit 1; }

/bin/hostname twbox-$HOSTID
/bin/hostname > /etc/hostname

cat <<EOF > /etc/hosts
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

172.16.0.1	twbox-$HOSTID
EOF

umount /var/host/current 2>/dev/null || true
mount --bind /var/host/twbox-${HOSTID} /var/host/current
