#!/bin/sh -eu

# Generate phonehome key
mkdir -p twpreload/phonehome
[ -f twpreload/phonehome/id_rsa ] || ssh-keygen -f twpreload/phonehome/id_rsa -N ""
[ -f twpreload/phonehome/config ] || cat <<'EOF' > twpreload/phonehome/config
# Example phonehome config, replace with sensible values
Host phonehome
    User phonehome
    HostName phonehome.net
EOF

ARCH=amd64

# NB: preboot-base.sh hard-codes debian backport version
# NB: /etc/resolv.conf must be replaced outside a --run, since libguestfs replaces it
# NB: Use `#--run ..` to comment out modules
virt-builder debian-10 \
    --output eias.${ARCH}.img --format raw \
    --hostname tutorweb-box \
    --arch amd64 \
    --timezone UTC \
    --copy-in 'conf/overlay-webserver/srv:/' \
    --copy-in 'twpreload:/' \
    --run conf/preboot-base.sh \
    --run conf/preboot-network.sh \
    --link /etc/resolvconf/run/resolv.conf:/etc/resolv.conf \
    --run conf/preboot-webserver.sh \
    --run conf/preboot-webserver-fakeinternet.sh \
    --run conf/preboot-webserver-shellinabox.sh \
    --run conf/preboot-network-wifiap.sh \
    --run conf/preboot-network-usbmodem.sh \
    --run conf/preboot-network-mbimmodem.sh \
    --run conf/preboot-network-phonehome.sh \
    --run conf/preboot-kiwix.sh \
    --run conf/preboot-tutorweb.sh \
    --run conf/preboot-kolibri.sh \
    `#--run conf/preboot-smileycoin.sh` \
    --no-logfile
