#!/bin/sh -eu

# Generate phonehome key
mkdir -p twpreload/phonehome
[ -f twpreload/phonehome/id_rsa ] || ssh-keygen -f twpreload/phonehome/id_rsa -N ""

# NB: preboot-base.sh hard-codes debian backport version
virt-builder debian-10 \
    --output eias.img --format raw \
    --hostname tutorweb-box \
    --root-password password:tuttuttut \
    --arch amd64 \
    --timezone UTC \
    --copy-in 'conf/overlay-webserver/srv:/' \
    --copy-in 'twpreload:/' \
    --run conf/preboot-base.sh \
    --run conf/preboot-network.sh \
    --run conf/preboot-network-phonehome.sh \
    --run conf/preboot-webserver.sh \
    --run conf/preboot-webserver-fakeinternet.sh \
    --run conf/preboot-webserver-shellinabox.sh \
    --run conf/preboot-kiwix.sh \
    --no-logfile
#    --run conf/preboot-kalite.sh \
#    --run conf/preboot-tutorweb.sh \
#    --run conf/preboot-smileycoin.sh \

# TODO: 
#br_chroot adduser --disabled-password --gecos \"\" --uid 1000 --gid 1000 tutor
#cat ./twpasswd | br_chroot chpasswd
#br_chroot usermod -a -G sudo tutor
