#!/bin/bash
set -eu

IMAGE="${1-debian-live-10.8.0-amd64-xfce.iso}"
[ -e "${IMAGE}" ] || {
    echo wget latest amd64-xfce.iso from https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/
    exit 1
}

CMD_LINE="qemu-system-x86_64 -m 2G -machine accel=kvm"

CMD_LINE="${CMD_LINE} -vga std -monitor stdio"

CMD_LINE="${CMD_LINE} -netdev bridge,br=eiasbr0,id=int_net"
CMD_LINE="${CMD_LINE} -device virtio-net,netdev=int_net,mac=$(printf 'DE:AD:BE:EF:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256)))"
CMD_LINE="${CMD_LINE} -drive format=raw,if=virtio,file=$IMAGE"

echo ${CMD_LINE}
eval ${CMD_LINE}
