#!/bin/sh -eu

CMD_LINE="qemu-system-x86_64 -m 4G -machine accel=kvm -usb -device usb-ehci,id=ehci"

# CMD_LINE="${CMD_LINE} -vga std -monitor stdio"
CMD_LINE="${CMD_LINE} -nographic -monitor none -serial stdio"

CMD_LINE="${CMD_LINE} -netdev bridge,br=eiasbr0,id=int_net"
CMD_LINE="${CMD_LINE} -device e1000,netdev=int_net,mac=DE:AD:BE:EF:01:01"
CMD_LINE="${CMD_LINE} -netdev user,id=ext_net"
CMD_LINE="${CMD_LINE} -device virtio-net,netdev=ext_net"

# qemu-img create -f qcow2 eias.twdata.qcow2 10G
# mkfs.ext4 -L twdata /dev/vdb
IMAGE="${1-eias.amd64.img}"
TWDATA_IMAGE="${2-eias.twdata.qcow2}"
[ -e ${IMAGE} ] && CMD_LINE="${CMD_LINE} -drive format=raw,if=virtio,file=$IMAGE"
[ -e ${TWDATA_IMAGE} ] && CMD_LINE="${CMD_LINE} -drive format=qcow2,if=virtio,file=${TWDATA_IMAGE}"

# Save current terminal settings (for restoring later)
# https://fragdev.com/blog/using-qemu-inside-terminal-serial-output
STTY_SETTINGS="$( stty -g )"

# Override Ctrl+c and Ctrl+z to prevent killing the VM in horrid ways
# ( Set to right bracket, can be changed if that combination is used )
stty intr ^]
stty susp ^]

echo ${CMD_LINE}
eval ${CMD_LINE}

# Reset the terminal
stty "$STTY_SETTINGS"
