#!/bin/sh -e

mount -o remount,rw /

usermod -aG systemd-journal www-data

echo 'mysql-server mysql-server/root_password password ""' | debconf-set-selections
echo 'mysql-server mysql-server/root_password_again password ""' | debconf-set-selections

apt-get update
apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y -t jessie-backports e2fsprogs nginx fcgiwrap
apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y mysql-server libmysqlclient-dev shellinabox
update-initramfs -k all -u
update-grub
grub-install /dev/sda

[ -f /var/local/kalite-bundle.deb ] && dpkg -i /var/local/kalite-bundle.deb
[ -d /var/kalite ] && {
    mv /var/kalite /var/kalite.default
    ln -s /var/local/var/kalite /var/kalite
}
