#!/bin/sh -e

mount -o remount,rw /

echo 'mysql-server mysql-server/root_password password ""' | debconf-set-selections
echo 'mysql-server mysql-server/root_password_again password ""' | debconf-set-selections

apt-get update
apt-get install -y -t jessie-backports e2fsprogs nginx
apt-get install -y mysql-server libmysqlclient-dev shellinabox
update-initramfs -k all -u
update-grub
grub-install /dev/sda
