#!/bin/sh -e
HOSTID="000000"
[ -f /sys/class/net/int0/address ] && HOSTID="$(/bin/sed 's/://g ; s/^.\{6\}//' /sys/class/net/int0/address)"

# Mount /var/local, or if it's not there then use a tmpfs
#TODO: Actually mount the other stick
mount -t tmpfs tmpfs /var/local

mkdir -p /var/local/etc
/bin/hostname twbox-$HOSTID
/bin/hostname > /var/local/etc/hostname
echo "twbox-${HOSTID}.tutor-web.net" > /var/local/etc/mailname

##### Systemd bodges
for dir in \
        /var/lib/systemd \
        /var/lib/container \
        /var/lib/dhcp \
        /var/cache \
        /var/log \
    ; do
    mkdir -p /var/local${dir}
done

##### DNSMasq
mkdir -p /var/local/etc/dnsmasq.d

##### nullmailer
mount -t tmpfs tmpfs /var/spool/nullmailer
mkdir -p /var/spool/nullmailer/queue
mkdir -p /var/spool/nullmailer/tmp
chown mail:root /var/spool/nullmailer/*

##### MySQL
[ -d /var/local/var/lib/mysql ] || {
    mkdir -p /var/local/var/lib/mysql
    [ -e /usr/bin/mysql_install_db ] && /usr/bin/mysql_install_db
}

##### Nginx
mkdir -p /var/local/var/log/nginx
touch /var/local/var/log/nginx/access.log
touch /var/local/var/log/nginx/error.log

##### Smileycoin
[ -d /var/local/var/lib/smly ] || {
  mkdir -p /var/local/var/lib/smly
  chown smly:staff /var/local/var/lib/smly
}
[ -f /var/lib/smly/smileycoin.conf ] || {
    RPCPASS="$(xxd -ps -l 22 /dev/urandom)"
    echo "rpcuser=smileycoinrpc" > /var/lib/smly/smileycoin.conf
    echo "rpcpassword=${RPCPASS}" >> /var/lib/smly/smileycoin.conf
}

##### Tutor-web
mkdir -p /var/local/srv/tutorweb.buildout
mkdir -p /var/local/srv/tutorweb.buildout/var/log
mount -t tmpfs tmpfs /srv/tutorweb.buildout/var/log
[ -f /var/local/srv/tutorweb.buildout/buildout.cfg ] || {
    MYSQLPASS="$(xxd -ps -l 22 /dev/urandom)"
    TWPASS="$(xxd -ps -l 22 /dev/urandom)"
    RPCPASS="$(awk -F= '/rpcpassword\=/ { print $2; }' /var/lib/smly/smileycoin.conf)"
    WALLETPASS="$(xxd -ps -l 22 /dev/urandom)"
    cat <<'EOF' > /var/local/srv/tutorweb.buildout/buildout.cfg
[buildout]
extends = cfgs/production.cfg
always-checkout = false
parts +=
    replicate-dump
    replicate-dump-mkdir
eggs +=
    MySQL-python
quizdb-url = mysql+mysqldb://tw_quizdb:${passwords:mysql}@localhost/tw_quizdb?charset=utf8
quizdb-coin-pass = ${passwords:smlyrpc}
quizdb-coin-walletpass = ${passwords:smlywallet}

[instance]
user = admin:${passwords:admin}

[passwords]
admin = ${TWPASS}
mysql = ${MYSQLPASS}
smlyrpc = ${RPCPASS}
smlywallet = ${WALLETPASS}
EOF
}

##### Phonehome
PORTRANGE="5"
[ "$HOSTID" = "7a6741" ] && { PORTRANGE="6"; }
[ "$HOSTID" = "7c7ba8" ] && { PORTRANGE="7"; }
[ "$HOSTID" = "7ccb04" ] && { PORTRANGE="8"; }
[ "$HOSTID" = "7cb5e1" ] && { PORTRANGE="9"; }
[ "$HOSTID" = "7ca4de" ] && { PORTRANGE="0"; }

mkdir -p /run/phonehome
cp /etc/phonehome/* /run/phonehome
[ -f /run/phonehome/config ] || {
    cat <<EOF > /run/phonehome/config
Host phonehome
    User phonehome
    HostName tutor-web.net
    LocalForward 9025 localhost:25
    RemoteForward 9${PORTRANGE}22 localhost:22
    RemoteForward 9${PORTRANGE}80 localhost:80
EOF
}
chown nobody:nogroup /run/phonehome/*
chmod 600 /run/phonehome/*

##### kiwix
echo "" > /run/kiwix-library.xml
ls -1 /srv/kiwix/*.{zim,zimaa} /var/local/srv/kiwix/*.{zim,zimaa} | xargs -L1 kiwix-manage /run/kiwix-library.xml add
