#!/bin/sh -e
HOSTID="$(/bin/sed 's/://g ; s/^.\{6\}//' /sys/class/net/int0/address)"
[ -n "$HOSTID" ] || { echo "No HOSTID"; exit 1; }

/bin/hostname twbox-$HOSTID
/bin/hostname > /etc/hostname

LOCATION="$LOCATION"
PORTRANGE="X"
[ "$HOSTID" = "7ca4de" ] && { LOCATION="spare"; PORTRANGE="0"; }

[ -d /var/host/twbox-${HOSTID} ] || {
    mkdir -- "/var/host/twbox-${HOSTID}"
}

umount /var/host/current 2>/dev/null || true
mount --bind /var/host/twbox-${HOSTID} /var/host/current

[ -f /var/host/current/hosts ] || {
    cat <<EOF > /var/host/current/hosts
127.0.0.1       localhost
127.0.0.22      smtp-relay
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

172.16.0.1      twbox twbox-${HOSTID} twbox-${HOSTID}.tutor-web.net box.tutor-web.net kiwix.tutor-web.net ka.tutor-web.net box.smileyco.in ${LOCATION}.tutor-web.net
EOF
}
[ -L /etc/hosts ] || {
    [ -e /etc/hosts ] && mv /etc/hosts /etc/hosts.o
    ln -s /var/host/current/hosts /etc/hosts
}

[ -f /var/host/current/mailname ] || {
    echo "twbox-${HOSTID}.tutor-web.net" > /var/host/current/mailname
}
[ -L /etc/mailname ] || {
    [ -e /etc/mailname ] && mv /etc/mailname /etc/hosts.o
    ln -s /var/host/current/mailname /etc/mailname
}

[ -L /var/lib/mysql ] || {
    /etc/init.d/mysql stop
    [ -e /var/lib/mysql ] && mv /var/lib/mysql /var/lib/mysql.o
    ln -s /var/host/current/mysql /var/lib/mysql
}
[ -d /var/host/current/mysql ] || {
    mkdir -p /var/host/current/mysql
    mysql_install_db
}

[ -f /var/host/current/nginx/redirect ] || {
    mkdir -p /var/host/current/nginx
    cat <<EOF > /var/host/current/nginx/redirect
server {
  listen [::]:80;
  listen      80;
  server_name box.tutor-web.net;

  location / {
    rewrite           ^(.*)$ http://${LOCATION}.tutor-web.net\$1 redirect;
  }
}
EOF
}
[ -L /etc/nginx/sites-enabled/default ] && rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/tw-proxy /etc/nginx/sites-enabled/tw-proxy
ln -sf /var/host/current/nginx/redirect /etc/nginx/sites-enabled/redirect

[ -f /var/host/current/buildout.cfg ] || {
    cat <<'EOF' > /var/host/current/buildout.cfg
[buildout]
extends = cfgs/production.cfg
always-checkout = false
parts +=
    replicate-dump
    replicate-dump-mkdir
eggs +=
    MySQL-python
quizdb-url = mysql+mysqldb://tw_quizdb:${passwords:mysql}@localhost/tw_quizdb?charset=utf8
quizdb-coin-pass = ${passwords:smlyrpc}
quizdb-coin-walletpass = ${passwords:smlywallet}

[instance]
user = admin:${passwords:admin}

[passwords]
admin = 
mysql = 
smlyrpc = 
smlywallet = 
EOF
}
[ -L /srv/tutorweb.buildout/buildout.cfg ] || ln -s /var/host/current/buildout.cfg /srv/tutorweb.buildout/buildout.cfg

[ -d /var/host/current/phonehome ] || mkdir -p /var/host/current/phonehome
[ -f /var/host/current/phonehome/id_rsa ] || {
    ssh-keygen -N "" -f /var/host/current/phonehome/id_rsa
    chown nobody:nogroup /var/host/current/phonehome/id_rsa*
}
[ -f /var/host/current/phonehome/config ] || {
    cat <<EOF > /var/host/current/phonehome/config
Host *
    LocalForward 9025 localhost:25
    RemoteForward 9${PORTRANGE}22 localhost:22
    RemoteForward 9${PORTRANGE}80 localhost:80
EOF
}

[ -d /var/host/current/smly ] || {
  mkdir -p /var/host/current/smly
  chown smly:staff /var/host/current/smly
}
[ -f /var/host/current/smly/smileycoin.conf ] || {
    RPCPASS="$(xxd -ps -l 22 /dev/urandom)"
    echo "rpcuser=smileycoinrpc" > /var/host/current/smly/smileycoin.conf
    echo "rpcpassword=${RPCPASS}" >> /var/host/current/smly/smileycoin.conf
}
