#!/bin/sh -e
HOSTID="000000"
[ -f /sys/class/net/int0/address ] && HOSTID="$(/bin/sed 's/://g ; s/^.\{6\}//' /sys/class/net/int0/address)"

# Mount /var/local, or if it's not there then use a tmpfs
#TODO: Actually mount the other stick
mount -t tmpfs tmpfs /var/local

mkdir -p /var/local/etc
/bin/hostname twbox-$HOSTID
/bin/hostname > /var/local/etc/hostname
echo "twbox-${HOSTID}.tutor-web.net" > /var/local/etc/mailname

##### Systemd bodges
for dir in \
        /var/lib/systemd \
        /var/lib/container \
        /var/lib/dhcp \
        /var/cache \
        /var/log \
    ; do
    mkdir -p /var/local${dir}
done

##### DNSMasq
mkdir -p /var/local/etc/dnsmasq.d

##### MySQL
[ -d /var/local/var/lib/mysql ] || {
    mkdir -p /var/local/var/lib/mysql
    [ -e /usr/bin/mysql_install_db ] && /usr/bin/mysql_install_db
}

##### Smileycoin
[ -d /var/local/var/lib/smly ] || {
  mkdir -p /var/local/var/lib/smly
  chown smly:staff /var/local/var/lib/smly
}
[ -f /var/lib/smly/smileycoin.conf ] || {
    RPCPASS="$(xxd -ps -l 22 /dev/urandom)"
    echo "rpcuser=smileycoinrpc" > /var/lib/smly/smileycoin.conf
    echo "rpcpassword=${RPCPASS}" >> /var/lib/smly/smileycoin.conf
}

##### Tutor-web
mkdir -p /var/local/srv/tutorweb.buildout
mkdir -p /var/local/srv/tutorweb.buildout/var/log
mount -t tmpfs tmpfs /srv/tutorweb.buildout/var/log
[ -f /var/local/srv/tutorweb.buildout/buildout.cfg ] || {
    MYSQLPASS="$(xxd -ps -l 22 /dev/urandom)"
    TWPASS="$(xxd -ps -l 22 /dev/urandom)"
    RPCPASS="$(awk -F= '/rpcpassword\=/ { print $2; }' /var/lib/smly/smileycoin.conf)"
    WALLETPASS="$(xxd -ps -l 22 /dev/urandom)"
    cat <<'EOF' > /var/local/srv/tutorweb.buildout/buildout.cfg
[buildout]
extends = cfgs/production.cfg
always-checkout = false
parts +=
    replicate-dump
    replicate-dump-mkdir
eggs +=
    MySQL-python
quizdb-url = mysql+mysqldb://tw_quizdb:${passwords:mysql}@localhost/tw_quizdb?charset=utf8
quizdb-coin-pass = ${passwords:smlyrpc}
quizdb-coin-walletpass = ${passwords:smlywallet}

[instance]
user = admin:${passwords:admin}

[passwords]
admin = ${TWPASS}
mysql = ${MYSQLPASS}
smlyrpc = ${RPCPASS}
smlywallet = ${WALLETPASS}
EOF
}

##### Phonehome
PORTRANGE="5"
[ "$HOSTID" = "7a6741" ] && { PORTRANGE="6"; }
[ "$HOSTID" = "7c7ba8" ] && { PORTRANGE="7"; }
[ "$HOSTID" = "7ccb04" ] && { PORTRANGE="8"; }
[ "$HOSTID" = "7cb5e1" ] && { PORTRANGE="9"; }
[ "$HOSTID" = "7ca4de" ] && { PORTRANGE="0"; }

mkdir -p /var/local/etc/phonehome
[ -f /var/local/etc/phonehome/known_hosts ] || {
    cat <<EOF > /var/local/etc/phonehome/known_hosts
|1|fyDx9+2kk4W3bDVbXSnhUo8pQ3k=|SUU625Nm1SjZZXhIuB4BNk5vIsA= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMaVIAuzuZM4iopQ6yjQLhyIf9kYDPBMtUAzQv+CHQxcYKC8ZZuoKoVb/8Z2FuSLdNoWuTi0jmkozAzBgRHpXhw=
|1|qL/GdmwB3i8nIMJiVgdhovQD7EI=|9E2PFIHNh6klm7NKZh41/l1QkwM= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMaVIAuzuZM4iopQ6yjQLhyIf9kYDPBMtUAzQv+CHQxcYKC8ZZuoKoVb/8Z2FuSLdNoWuTi0jmkozAzBgRHpXhw=
EOF
}
[ -f /var/local/etc/phonehome/id_rsa ] || {
    ssh-keygen -N "" -f /var/local/etc/phonehome/id_rsa
    chown nobody:nogroup /var/local/etc/phonehome/id_rsa*
}
[ -f /var/local/etc/phonehome/config ] || {
    cat <<EOF > /var/local/etc/phonehome/config
Host phonehome
    User phonehome
    HostName tutor-web.net
    LocalForward 9025 localhost:25
    RemoteForward 9${PORTRANGE}22 localhost:22
    RemoteForward 9${PORTRANGE}80 localhost:80
EOF
}
