#!/bin/sh
TERM=dumb

echo "Content-type: text/plain;charset=utf-8"
echo "Cache-Control: no-store, no-cache, must-revalidate, max-age=0"
echo ""
echo ""

echo "***** Important Processes *****************************************************"
for p in phonehome smly tutor-web mysql kiwix ka nginx; do
    systemctl status -l $p
done
echo "*******************************************************************************\n"

echo "***** Disk status *************************************************************"
df -h
echo ""
mount
echo ""
lsusb
echo "*******************************************************************************\n"

echo "***** Networking status *******************************************************"
ip addr
echo ""
ip route
#echo ""
#mtr --report-wide --report-cycles=3 8.8.8.8
echo ""
cat /run/dnsmasq.leases
echo "*******************************************************************************\n"

echo "***** Full process list *******************************************************"
systemctl --no-pager
echo "*******************************************************************************\n"

echo "***** System log **************************************************************"
/bin/journalctl --system --no-pager
echo "*******************************************************************************\n"
